# HexNicks created by Majekdor on August 27th, 2020 | Need help? Message me on Discord @Majekdor#6346

# Maximum number of characters allowed in a nickname (not including any color codes)
max-length: 20

# Minimum number of characters allowed in a nickname (not including any color codes)
min-length: 3

# If set to true only players with permission hexnicks.use will be able to use /nick (false by default)
use-permissions: false

# If set to true then players nicknames will be shown in the tablist
tab-nicknames: false

# If set to true join and leave messages will use the player's nickname instead of real name
joinleave-message-nicks: false

# If set to true death messages will use the player's nickname instead of real name
death-message-nicks: false

# Toggle whether or not the name above a player's head is their nickname
player-head-nick: false
