# HexNicks created by Majekdor on August 27th, 2020 | Need help? Message me on Discord @Majekdor#6346

# Maximum number of characters allowed in a nickname (not including any color codes)
max-length: 20

# Minimum number of characters allowed in a nickname (not including any color codes)
min-length: 3

# If set to true only players with permission hexnicks.use will be able to use /nick (false by default)
use-permissions: false

# If set to true then players nicknames will be shown in the tablist
tab-nicknames: false

# If set to true join and leave messages will use the player's nickname instead of real name
# The formatting will only be used if joinleave-message-nicks is set to true
joinleave-message-nicks: false
join-message-format: '&7&l > &b%nickname% &rjoined the game'
leave-message-format: '&7&l > &b%nickname% &rleft the game'

# If set to true death messages will use the player's nickname instead of real name
death-message-nicks: false


# Database settings
# Only enable this if you know what you're doing and have an existing database
database-enabled: false
host: ''
port: ''
database: ''
username: ''
password: ''
use-ssl: false
