name: HexNicks
version: 1.1.4
main: me.majekdor.hexnicks.HexNicks
api-version: 1.16
authors: [Majekdor]
description: Allow users to give themselves nicknames using hex color codes and use hex color codes in chat.
commands:
  nick:
    description: Change your nickname.
    aliases: [nickname]
  nickcolor:
    description: Change just the color of your nickname.
    aliases: [colornick]
  nonick:
    description: Remove you nickname.

permissions:
  hexnicks.use:
    description: Use /nick if use-permissions is enabled in the config.yml
    children: [hexnicks.changecolor]
  hexnicks.changecolor:
    description: Use /nickcolor if use-permissions is enabled in the config.yml
