name: HexNicks
version: 1.4.1
main: dev.majek.hexnicks.HexNicks
api-version: 1.13
authors: [Majekdor]
description: Allow users to give themselves nicknames using hex color codes and use hex color codes in chat.
softdepend: [PlaceholderAPI]
commands:
  nick:
    description: Change your nickname.
    aliases: [nickname]
    usage: /nick [player] <nickname> | Use /nick help for more
  nickcolor:
    description: Change just the color of your nickname.
    aliases: [colornick]
    usage: /nick <colorcode>
  nonick:
    description: Remove you nickname.
    usage: /nonick [player]
  hexreload:
    description: Reload the plugin config file and data file.

permissions:
  hexnicks.use:
    description: Use /nick if use-permissions is enabled in the config.yml
    children: [hexnicks.changecolor, hexnicks.colors.normal, hexnicks.colors.hex]
  hexnicks.changecolor:
    description: Use /nickcolor if use-permissions is enabled in the config.yml
  hexnicks.colors.normal:
    description: Ability to use normal color codes in nicknames
  hexnicks.colors.hex:
    description: Ability to use hex color codes in nicknames
  hexnicks.admin:
    description: Ability to run HexNicks admin commands.
    default: op
  hexnicks.chat:
    description: Ability to use color codes in chat if use-permissions is enabled in the config.yml
    default: op
